<a href="https://colab.research.google.com/github/01PrathamS/ML-classification/blob/main/classification_all.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

In [2]:
dataset = pd.read_csv('/content/Social_Network_Ads.csv')
X = dataset.iloc[:, :-1].values 
y = dataset.iloc[:, -1].values 

In [3]:
## features scaling 

from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [4]:
from sklearn.preprocessing import StandardScaler 

sc = StandardScaler() 
X_train = sc.fit_transform(X_train) 
X_test = sc.transform(X_test)

Logistic Regression

In [14]:

# from sklearn.linear_model import LogisticRegression 

# classifier = LogisticRegression(random_state=0) 
# classifier.fit(X_train, y_train)

In [15]:
# classifier.predict(sc.transform([[30,800000]]))

In [16]:
# y_pred = classifier.predict(X_test)

In [17]:
# from sklearn.metrics import confusion_matrix, accuracy_score 

# cm = confusion_matrix(y_pred, y_test) 
# print(cm) 
# accuracy_score(y_pred, y_test) 


K Neighbors Classifier


In [18]:
# from sklearn.neighbors import KNeighborsClassifier 

# classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2) 
# classifier.fit(X_train, y_train) 

KNeighborsClassifier()

In [21]:
# y_pred = classifier.predict(X_test)

In [22]:
# from sklearn.metrics import confusion_matrix, accuracy_score 

# cm = confusion_matrix(y_pred, y_test) 
# print(cm) 
# accuracy_score(y_pred, y_test)

[[55  1]
 [ 3 21]]


0.95

Support Vector Machine

In [28]:
# from sklearn.svm import SVC 

# classifier = SVC(kernel="linear", random_state=0) 
# classifier.fit(X_train, y_train)

In [29]:
# classifier.predict(sc.transform([[30, 80000]]))

In [30]:
# y_pred = classifier.predict(X_test) 


In [31]:
# from sklearn.metrics import confusion_matrix, accuracy_score 

# cm = confusion_matrix(y_pred, y_test) 
# print(cm) 

# accuracy_score(y_pred, y_test)

kernel SVM

In [32]:
# from sklearn.svm import SVC

# classifier = SVC(kernel='rbf', random_state=0) 
# classifier.fit(X_train, y_train)

SVC(random_state=0)

In [34]:
# classifier.predict(sc.transform([[30, 800000]]))

array([1])

In [36]:
# from sklearn.metrics import confusion_matrix, accuracy_score 

# cm = confusion_matrix(y_pred, y_test) 
# print(cm) 
# accuracy_score(y_pred, y_test)

[[57  6]
 [ 1 16]]


0.9125

naive bayes


In [37]:
# from sklearn.naive_bayes import GaussianNB 

# classifier = GaussianNB() 
# classifier.fit(X_train, y_train)

GaussianNB()

In [39]:
# classifier.predict(sc.transform([[30, 800000]]))

array([1])

In [47]:
# y_pred = classifier.predict(X_test)

In [48]:
# from sklearn.metrics import confusion_matrix, accuracy_score 

# cm = confusion_matrix(y_pred, y_test) 
# print(cm) 
# accuracy_score(y_pred, y_test)

[[55  4]
 [ 3 18]]


0.9125

decision tree 

In [49]:
# from sklearn.tree import DecisionTreeClassifier 

# classifier = DecisionTreeClassifier(criterion='entropy', random_state=0) 
# classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [51]:
# classifier.predict(sc.transform([[30, 800000]]))

array([1])

In [52]:
# y_pred = classifier.predict(X_test)

In [53]:
# from sklearn.metrics import confusion_matrix, accuracy_score 

# cm = confusion_matrix(y_pred, y_test) 
# print(cm) 
# accuracy_score(y_pred, y_test)

[[53  3]
 [ 5 19]]


0.9

random forest 


In [55]:
from sklearn.ensemble import RandomForestClassifier 

classifier = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0) 
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [57]:
classifier.predict(sc.transform([[30, 800000]]))

array([1])

In [58]:
y_pred = classifier.predict(X_test)

In [60]:
from sklearn.metrics import confusion_matrix, accuracy_score 

cm = confusion_matrix(y_pred, y_test) 
print(cm) 
accuracy_score(y_pred, y_test)

[[54  3]
 [ 4 19]]


0.9125